/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AyudaRouteImport } from './routes/ayuda'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAsistenciaRouteImport } from './routes/_authenticated/asistencia'
import { Route as AuthenticatedBienestarRouteImport } from './routes/_authenticated/bienestar'
import { Route as AuthenticatedCalendarioRouteImport } from './routes/_authenticated/calendario'
import { Route as AuthenticatedCallUpsRouteImport } from './routes/_authenticated/call-ups'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEntrenosRouteImport } from './routes/_authenticated/entrenos'
import { Route as AuthenticatedEquipoRouteImport } from './routes/_authenticated/equipo'
import { Route as AuthenticatedEstadisticasRouteImport } from './routes/_authenticated/estadisticas'
import { Route as AuthenticatedFormulariosRouteImport } from './routes/_authenticated/formularios'
import { Route as AuthenticatedHqRouteImport } from './routes/_authenticated/hq'
import { Route as AuthenticatedInicioRouteImport } from './routes/_authenticated/inicio'
import { Route as AuthenticatedMiCalendarioRouteImport } from './routes/_authenticated/mi-calendario'
import { Route as AuthenticatedMiPerfilRouteImport } from './routes/_authenticated/mi-perfil'
import { Route as AuthenticatedMisConvocatoriasRouteImport } from './routes/_authenticated/mis-convocatorias'
import { Route as AuthenticatedMisEstadisticasRouteImport } from './routes/_authenticated/mis-estadisticas'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedPanelFulltimeRouteImport } from './routes/_authenticated/panel-fulltime'
import { Route as AuthenticatedPerfilEntrenadorRouteImport } from './routes/_authenticated/perfil-entrenador'
import { Route as AuthenticatedRosterRouteImport } from './routes/_authenticated/roster'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as UnirseEquipoTokenRouteImport } from './routes/unirse-equipo.$token'
import { Route as UnirseTokenRouteImport } from './routes/unirse.$token'
import { Route as AuthenticatedCallUpsIndexRouteImport } from './routes/_authenticated/call-ups.index'
import { Route as AuthenticatedCallUpsIdRouteImport } from './routes/_authenticated/call-ups.$id'
import { Route as AuthenticatedCallUpsNewRouteImport } from './routes/_authenticated/call-ups.new'
import { Route as AuthenticatedCotizacionIdRouteImport } from './routes/_authenticated/cotizacion.$id'
import { Route as AuthenticatedEntrenosIndexRouteImport } from './routes/_authenticated/entrenos.index'
import { Route as AuthenticatedEntrenosNewRouteImport } from './routes/_authenticated/entrenos.new'
import { Route as AuthenticatedHojaIdRouteImport } from './routes/_authenticated/hoja.$id'
import { Route as AuthenticatedHqIndexRouteImport } from './routes/_authenticated/hq.index'
import { Route as AuthenticatedHqSeccionRouteImport } from './routes/_authenticated/hq.$seccion'
import { Route as AuthenticatedHqAutomatizacionesRouteImport } from './routes/_authenticated/hq.automatizaciones'
import { Route as AuthenticatedHqCalendarioRouteImport } from './routes/_authenticated/hq.calendario'
import { Route as AuthenticatedHqContenidoRouteImport } from './routes/_authenticated/hq.contenido'
import { Route as AuthenticatedHqCotizacionesRouteImport } from './routes/_authenticated/hq.cotizaciones'
import { Route as AuthenticatedHqCrmRouteImport } from './routes/_authenticated/hq.crm'
import { Route as AuthenticatedHqInboxRouteImport } from './routes/_authenticated/hq.inbox'
import { Route as AuthenticatedHqNotificacionesRouteImport } from './routes/_authenticated/hq.notificaciones'
import { Route as AuthenticatedHqProyectosRouteImport } from './routes/_authenticated/hq.proyectos'
import { Route as AuthenticatedHqReunionesRouteImport } from './routes/_authenticated/hq.reuniones'
import { Route as AuthenticatedHqTareasRouteImport } from './routes/_authenticated/hq.tareas'
import { Route as ApiPublicCronRemindersRouteImport } from './routes/api/public/cron/reminders'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AyudaRoute = AyudaRouteImport.update({
  id: '/ayuda',
  path: '/ayuda',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAsistenciaRoute = AuthenticatedAsistenciaRouteImport.update({
  id: '/asistencia',
  path: '/asistencia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBienestarRoute = AuthenticatedBienestarRouteImport.update({
  id: '/bienestar',
  path: '/bienestar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarioRoute = AuthenticatedCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCallUpsRoute = AuthenticatedCallUpsRouteImport.update({
  id: '/call-ups',
  path: '/call-ups',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEntrenosRoute = AuthenticatedEntrenosRouteImport.update({
  id: '/entrenos',
  path: '/entrenos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEquipoRoute = AuthenticatedEquipoRouteImport.update({
  id: '/equipo',
  path: '/equipo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEstadisticasRoute =
  AuthenticatedEstadisticasRouteImport.update({
    id: '/estadisticas',
    path: '/estadisticas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFormulariosRoute =
  AuthenticatedFormulariosRouteImport.update({
    id: '/formularios',
    path: '/formularios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHqRoute = AuthenticatedHqRouteImport.update({
  id: '/hq',
  path: '/hq',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInicioRoute = AuthenticatedInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMiCalendarioRoute =
  AuthenticatedMiCalendarioRouteImport.update({
    id: '/mi-calendario',
    path: '/mi-calendario',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMiPerfilRoute = AuthenticatedMiPerfilRouteImport.update({
  id: '/mi-perfil',
  path: '/mi-perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMisConvocatoriasRoute =
  AuthenticatedMisConvocatoriasRouteImport.update({
    id: '/mis-convocatorias',
    path: '/mis-convocatorias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMisEstadisticasRoute =
  AuthenticatedMisEstadisticasRouteImport.update({
    id: '/mis-estadisticas',
    path: '/mis-estadisticas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPanelFulltimeRoute =
  AuthenticatedPanelFulltimeRouteImport.update({
    id: '/panel-fulltime',
    path: '/panel-fulltime',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPerfilEntrenadorRoute =
  AuthenticatedPerfilEntrenadorRouteImport.update({
    id: '/perfil-entrenador',
    path: '/perfil-entrenador',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRosterRoute = AuthenticatedRosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const UnirseEquipoTokenRoute = UnirseEquipoTokenRouteImport.update({
  id: '/unirse-equipo/$token',
  path: '/unirse-equipo/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const UnirseTokenRoute = UnirseTokenRouteImport.update({
  id: '/unirse/$token',
  path: '/unirse/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCallUpsIndexRoute =
  AuthenticatedCallUpsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCallUpsRoute,
  } as any)
const AuthenticatedCallUpsIdRoute = AuthenticatedCallUpsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedCallUpsRoute,
} as any)
const AuthenticatedCallUpsNewRoute = AuthenticatedCallUpsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedCallUpsRoute,
} as any)
const AuthenticatedCotizacionIdRoute =
  AuthenticatedCotizacionIdRouteImport.update({
    id: '/cotizacion/$id',
    path: '/cotizacion/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEntrenosIndexRoute =
  AuthenticatedEntrenosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEntrenosRoute,
  } as any)
const AuthenticatedEntrenosNewRoute =
  AuthenticatedEntrenosNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedEntrenosRoute,
  } as any)
const AuthenticatedHojaIdRoute = AuthenticatedHojaIdRouteImport.update({
  id: '/hoja/$id',
  path: '/hoja/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHqIndexRoute = AuthenticatedHqIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedHqRoute,
} as any)
const AuthenticatedHqSeccionRoute = AuthenticatedHqSeccionRouteImport.update({
  id: '/$seccion',
  path: '/$seccion',
  getParentRoute: () => AuthenticatedHqRoute,
} as any)
const AuthenticatedHqAutomatizacionesRoute =
  AuthenticatedHqAutomatizacionesRouteImport.update({
    id: '/automatizaciones',
    path: '/automatizaciones',
    getParentRoute: () => AuthenticatedHqRoute,
  } as any)
const AuthenticatedHqCalendarioRoute =
  AuthenticatedHqCalendarioRouteImport.update({
    id: '/calendario',
    path: '/calendario',
    getParentRoute: () => AuthenticatedHqRoute,
  } as any)
const AuthenticatedHqContenidoRoute =
  AuthenticatedHqContenidoRouteImport.update({
    id: '/contenido',
    path: '/contenido',
    getParentRoute: () => AuthenticatedHqRoute,
  } as any)
const AuthenticatedHqCotizacionesRoute =
  AuthenticatedHqCotizacionesRouteImport.update({
    id: '/cotizaciones',
    path: '/cotizaciones',
    getParentRoute: () => AuthenticatedHqRoute,
  } as any)
const AuthenticatedHqCrmRoute = AuthenticatedHqCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedHqRoute,
} as any)
const AuthenticatedHqInboxRoute = AuthenticatedHqInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedHqRoute,
} as any)
const AuthenticatedHqNotificacionesRoute =
  AuthenticatedHqNotificacionesRouteImport.update({
    id: '/notificaciones',
    path: '/notificaciones',
    getParentRoute: () => AuthenticatedHqRoute,
  } as any)
const AuthenticatedHqProyectosRoute =
  AuthenticatedHqProyectosRouteImport.update({
    id: '/proyectos',
    path: '/proyectos',
    getParentRoute: () => AuthenticatedHqRoute,
  } as any)
const AuthenticatedHqReunionesRoute =
  AuthenticatedHqReunionesRouteImport.update({
    id: '/reuniones',
    path: '/reuniones',
    getParentRoute: () => AuthenticatedHqRoute,
  } as any)
const AuthenticatedHqTareasRoute = AuthenticatedHqTareasRouteImport.update({
  id: '/tareas',
  path: '/tareas',
  getParentRoute: () => AuthenticatedHqRoute,
} as any)
const ApiPublicCronRemindersRoute = ApiPublicCronRemindersRouteImport.update({
  id: '/api/public/cron/reminders',
  path: '/api/public/cron/reminders',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/ayuda': typeof AyudaRoute
  '/privacidad': typeof PrivacidadRoute
  '/reset-password': typeof ResetPasswordRoute
  '/asistencia': typeof AuthenticatedAsistenciaRoute
  '/bienestar': typeof AuthenticatedBienestarRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/call-ups': typeof AuthenticatedCallUpsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/entrenos': typeof AuthenticatedEntrenosRouteWithChildren
  '/equipo': typeof AuthenticatedEquipoRoute
  '/estadisticas': typeof AuthenticatedEstadisticasRoute
  '/formularios': typeof AuthenticatedFormulariosRoute
  '/hq': typeof AuthenticatedHqRouteWithChildren
  '/inicio': typeof AuthenticatedInicioRoute
  '/mi-calendario': typeof AuthenticatedMiCalendarioRoute
  '/mi-perfil': typeof AuthenticatedMiPerfilRoute
  '/mis-convocatorias': typeof AuthenticatedMisConvocatoriasRoute
  '/mis-estadisticas': typeof AuthenticatedMisEstadisticasRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/panel-fulltime': typeof AuthenticatedPanelFulltimeRoute
  '/perfil-entrenador': typeof AuthenticatedPerfilEntrenadorRoute
  '/roster': typeof AuthenticatedRosterRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/unirse-equipo/$token': typeof UnirseEquipoTokenRoute
  '/unirse/$token': typeof UnirseTokenRoute
  '/call-ups/$id': typeof AuthenticatedCallUpsIdRoute
  '/call-ups/new': typeof AuthenticatedCallUpsNewRoute
  '/cotizacion/$id': typeof AuthenticatedCotizacionIdRoute
  '/entrenos/new': typeof AuthenticatedEntrenosNewRoute
  '/hoja/$id': typeof AuthenticatedHojaIdRoute
  '/hq/$seccion': typeof AuthenticatedHqSeccionRoute
  '/hq/automatizaciones': typeof AuthenticatedHqAutomatizacionesRoute
  '/hq/calendario': typeof AuthenticatedHqCalendarioRoute
  '/hq/contenido': typeof AuthenticatedHqContenidoRoute
  '/hq/cotizaciones': typeof AuthenticatedHqCotizacionesRoute
  '/hq/crm': typeof AuthenticatedHqCrmRoute
  '/hq/inbox': typeof AuthenticatedHqInboxRoute
  '/hq/notificaciones': typeof AuthenticatedHqNotificacionesRoute
  '/hq/proyectos': typeof AuthenticatedHqProyectosRoute
  '/hq/reuniones': typeof AuthenticatedHqReunionesRoute
  '/hq/tareas': typeof AuthenticatedHqTareasRoute
  '/call-ups/': typeof AuthenticatedCallUpsIndexRoute
  '/entrenos/': typeof AuthenticatedEntrenosIndexRoute
  '/hq/': typeof AuthenticatedHqIndexRoute
  '/api/public/cron/reminders': typeof ApiPublicCronRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/ayuda': typeof AyudaRoute
  '/privacidad': typeof PrivacidadRoute
  '/reset-password': typeof ResetPasswordRoute
  '/asistencia': typeof AuthenticatedAsistenciaRoute
  '/bienestar': typeof AuthenticatedBienestarRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/equipo': typeof AuthenticatedEquipoRoute
  '/estadisticas': typeof AuthenticatedEstadisticasRoute
  '/formularios': typeof AuthenticatedFormulariosRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/mi-calendario': typeof AuthenticatedMiCalendarioRoute
  '/mi-perfil': typeof AuthenticatedMiPerfilRoute
  '/mis-convocatorias': typeof AuthenticatedMisConvocatoriasRoute
  '/mis-estadisticas': typeof AuthenticatedMisEstadisticasRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/panel-fulltime': typeof AuthenticatedPanelFulltimeRoute
  '/perfil-entrenador': typeof AuthenticatedPerfilEntrenadorRoute
  '/roster': typeof AuthenticatedRosterRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/unirse-equipo/$token': typeof UnirseEquipoTokenRoute
  '/unirse/$token': typeof UnirseTokenRoute
  '/call-ups/$id': typeof AuthenticatedCallUpsIdRoute
  '/call-ups/new': typeof AuthenticatedCallUpsNewRoute
  '/cotizacion/$id': typeof AuthenticatedCotizacionIdRoute
  '/entrenos/new': typeof AuthenticatedEntrenosNewRoute
  '/hoja/$id': typeof AuthenticatedHojaIdRoute
  '/hq/$seccion': typeof AuthenticatedHqSeccionRoute
  '/hq/automatizaciones': typeof AuthenticatedHqAutomatizacionesRoute
  '/hq/calendario': typeof AuthenticatedHqCalendarioRoute
  '/hq/contenido': typeof AuthenticatedHqContenidoRoute
  '/hq/cotizaciones': typeof AuthenticatedHqCotizacionesRoute
  '/hq/crm': typeof AuthenticatedHqCrmRoute
  '/hq/inbox': typeof AuthenticatedHqInboxRoute
  '/hq/notificaciones': typeof AuthenticatedHqNotificacionesRoute
  '/hq/proyectos': typeof AuthenticatedHqProyectosRoute
  '/hq/reuniones': typeof AuthenticatedHqReunionesRoute
  '/hq/tareas': typeof AuthenticatedHqTareasRoute
  '/call-ups': typeof AuthenticatedCallUpsIndexRoute
  '/entrenos': typeof AuthenticatedEntrenosIndexRoute
  '/hq': typeof AuthenticatedHqIndexRoute
  '/api/public/cron/reminders': typeof ApiPublicCronRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/ayuda': typeof AyudaRoute
  '/privacidad': typeof PrivacidadRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/asistencia': typeof AuthenticatedAsistenciaRoute
  '/_authenticated/bienestar': typeof AuthenticatedBienestarRoute
  '/_authenticated/calendario': typeof AuthenticatedCalendarioRoute
  '/_authenticated/call-ups': typeof AuthenticatedCallUpsRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/entrenos': typeof AuthenticatedEntrenosRouteWithChildren
  '/_authenticated/equipo': typeof AuthenticatedEquipoRoute
  '/_authenticated/estadisticas': typeof AuthenticatedEstadisticasRoute
  '/_authenticated/formularios': typeof AuthenticatedFormulariosRoute
  '/_authenticated/hq': typeof AuthenticatedHqRouteWithChildren
  '/_authenticated/inicio': typeof AuthenticatedInicioRoute
  '/_authenticated/mi-calendario': typeof AuthenticatedMiCalendarioRoute
  '/_authenticated/mi-perfil': typeof AuthenticatedMiPerfilRoute
  '/_authenticated/mis-convocatorias': typeof AuthenticatedMisConvocatoriasRoute
  '/_authenticated/mis-estadisticas': typeof AuthenticatedMisEstadisticasRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/panel-fulltime': typeof AuthenticatedPanelFulltimeRoute
  '/_authenticated/perfil-entrenador': typeof AuthenticatedPerfilEntrenadorRoute
  '/_authenticated/roster': typeof AuthenticatedRosterRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/unirse-equipo/$token': typeof UnirseEquipoTokenRoute
  '/unirse/$token': typeof UnirseTokenRoute
  '/_authenticated/call-ups/$id': typeof AuthenticatedCallUpsIdRoute
  '/_authenticated/call-ups/new': typeof AuthenticatedCallUpsNewRoute
  '/_authenticated/cotizacion/$id': typeof AuthenticatedCotizacionIdRoute
  '/_authenticated/entrenos/new': typeof AuthenticatedEntrenosNewRoute
  '/_authenticated/hoja/$id': typeof AuthenticatedHojaIdRoute
  '/_authenticated/hq/$seccion': typeof AuthenticatedHqSeccionRoute
  '/_authenticated/hq/automatizaciones': typeof AuthenticatedHqAutomatizacionesRoute
  '/_authenticated/hq/calendario': typeof AuthenticatedHqCalendarioRoute
  '/_authenticated/hq/contenido': typeof AuthenticatedHqContenidoRoute
  '/_authenticated/hq/cotizaciones': typeof AuthenticatedHqCotizacionesRoute
  '/_authenticated/hq/crm': typeof AuthenticatedHqCrmRoute
  '/_authenticated/hq/inbox': typeof AuthenticatedHqInboxRoute
  '/_authenticated/hq/notificaciones': typeof AuthenticatedHqNotificacionesRoute
  '/_authenticated/hq/proyectos': typeof AuthenticatedHqProyectosRoute
  '/_authenticated/hq/reuniones': typeof AuthenticatedHqReunionesRoute
  '/_authenticated/hq/tareas': typeof AuthenticatedHqTareasRoute
  '/_authenticated/call-ups/': typeof AuthenticatedCallUpsIndexRoute
  '/_authenticated/entrenos/': typeof AuthenticatedEntrenosIndexRoute
  '/_authenticated/hq/': typeof AuthenticatedHqIndexRoute
  '/api/public/cron/reminders': typeof ApiPublicCronRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/ayuda'
    | '/privacidad'
    | '/reset-password'
    | '/asistencia'
    | '/bienestar'
    | '/calendario'
    | '/call-ups'
    | '/dashboard'
    | '/entrenos'
    | '/equipo'
    | '/estadisticas'
    | '/formularios'
    | '/hq'
    | '/inicio'
    | '/mi-calendario'
    | '/mi-perfil'
    | '/mis-convocatorias'
    | '/mis-estadisticas'
    | '/onboarding'
    | '/panel-fulltime'
    | '/perfil-entrenador'
    | '/roster'
    | '/auth/callback'
    | '/unirse-equipo/$token'
    | '/unirse/$token'
    | '/call-ups/$id'
    | '/call-ups/new'
    | '/cotizacion/$id'
    | '/entrenos/new'
    | '/hoja/$id'
    | '/hq/$seccion'
    | '/hq/automatizaciones'
    | '/hq/calendario'
    | '/hq/contenido'
    | '/hq/cotizaciones'
    | '/hq/crm'
    | '/hq/inbox'
    | '/hq/notificaciones'
    | '/hq/proyectos'
    | '/hq/reuniones'
    | '/hq/tareas'
    | '/call-ups/'
    | '/entrenos/'
    | '/hq/'
    | '/api/public/cron/reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/ayuda'
    | '/privacidad'
    | '/reset-password'
    | '/asistencia'
    | '/bienestar'
    | '/calendario'
    | '/dashboard'
    | '/equipo'
    | '/estadisticas'
    | '/formularios'
    | '/inicio'
    | '/mi-calendario'
    | '/mi-perfil'
    | '/mis-convocatorias'
    | '/mis-estadisticas'
    | '/onboarding'
    | '/panel-fulltime'
    | '/perfil-entrenador'
    | '/roster'
    | '/auth/callback'
    | '/unirse-equipo/$token'
    | '/unirse/$token'
    | '/call-ups/$id'
    | '/call-ups/new'
    | '/cotizacion/$id'
    | '/entrenos/new'
    | '/hoja/$id'
    | '/hq/$seccion'
    | '/hq/automatizaciones'
    | '/hq/calendario'
    | '/hq/contenido'
    | '/hq/cotizaciones'
    | '/hq/crm'
    | '/hq/inbox'
    | '/hq/notificaciones'
    | '/hq/proyectos'
    | '/hq/reuniones'
    | '/hq/tareas'
    | '/call-ups'
    | '/entrenos'
    | '/hq'
    | '/api/public/cron/reminders'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/ayuda'
    | '/privacidad'
    | '/reset-password'
    | '/_authenticated/asistencia'
    | '/_authenticated/bienestar'
    | '/_authenticated/calendario'
    | '/_authenticated/call-ups'
    | '/_authenticated/dashboard'
    | '/_authenticated/entrenos'
    | '/_authenticated/equipo'
    | '/_authenticated/estadisticas'
    | '/_authenticated/formularios'
    | '/_authenticated/hq'
    | '/_authenticated/inicio'
    | '/_authenticated/mi-calendario'
    | '/_authenticated/mi-perfil'
    | '/_authenticated/mis-convocatorias'
    | '/_authenticated/mis-estadisticas'
    | '/_authenticated/onboarding'
    | '/_authenticated/panel-fulltime'
    | '/_authenticated/perfil-entrenador'
    | '/_authenticated/roster'
    | '/auth/callback'
    | '/unirse-equipo/$token'
    | '/unirse/$token'
    | '/_authenticated/call-ups/$id'
    | '/_authenticated/call-ups/new'
    | '/_authenticated/cotizacion/$id'
    | '/_authenticated/entrenos/new'
    | '/_authenticated/hoja/$id'
    | '/_authenticated/hq/$seccion'
    | '/_authenticated/hq/automatizaciones'
    | '/_authenticated/hq/calendario'
    | '/_authenticated/hq/contenido'
    | '/_authenticated/hq/cotizaciones'
    | '/_authenticated/hq/crm'
    | '/_authenticated/hq/inbox'
    | '/_authenticated/hq/notificaciones'
    | '/_authenticated/hq/proyectos'
    | '/_authenticated/hq/reuniones'
    | '/_authenticated/hq/tareas'
    | '/_authenticated/call-ups/'
    | '/_authenticated/entrenos/'
    | '/_authenticated/hq/'
    | '/api/public/cron/reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  AyudaRoute: typeof AyudaRoute
  PrivacidadRoute: typeof PrivacidadRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  UnirseEquipoTokenRoute: typeof UnirseEquipoTokenRoute
  UnirseTokenRoute: typeof UnirseTokenRoute
  ApiPublicCronRemindersRoute: typeof ApiPublicCronRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ayuda': {
      id: '/ayuda'
      path: '/ayuda'
      fullPath: '/ayuda'
      preLoaderRoute: typeof AyudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/asistencia': {
      id: '/_authenticated/asistencia'
      path: '/asistencia'
      fullPath: '/asistencia'
      preLoaderRoute: typeof AuthenticatedAsistenciaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bienestar': {
      id: '/_authenticated/bienestar'
      path: '/bienestar'
      fullPath: '/bienestar'
      preLoaderRoute: typeof AuthenticatedBienestarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendario': {
      id: '/_authenticated/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AuthenticatedCalendarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/call-ups': {
      id: '/_authenticated/call-ups'
      path: '/call-ups'
      fullPath: '/call-ups'
      preLoaderRoute: typeof AuthenticatedCallUpsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entrenos': {
      id: '/_authenticated/entrenos'
      path: '/entrenos'
      fullPath: '/entrenos'
      preLoaderRoute: typeof AuthenticatedEntrenosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipo': {
      id: '/_authenticated/equipo'
      path: '/equipo'
      fullPath: '/equipo'
      preLoaderRoute: typeof AuthenticatedEquipoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estadisticas': {
      id: '/_authenticated/estadisticas'
      path: '/estadisticas'
      fullPath: '/estadisticas'
      preLoaderRoute: typeof AuthenticatedEstadisticasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/formularios': {
      id: '/_authenticated/formularios'
      path: '/formularios'
      fullPath: '/formularios'
      preLoaderRoute: typeof AuthenticatedFormulariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hq': {
      id: '/_authenticated/hq'
      path: '/hq'
      fullPath: '/hq'
      preLoaderRoute: typeof AuthenticatedHqRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inicio': {
      id: '/_authenticated/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof AuthenticatedInicioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mi-calendario': {
      id: '/_authenticated/mi-calendario'
      path: '/mi-calendario'
      fullPath: '/mi-calendario'
      preLoaderRoute: typeof AuthenticatedMiCalendarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mi-perfil': {
      id: '/_authenticated/mi-perfil'
      path: '/mi-perfil'
      fullPath: '/mi-perfil'
      preLoaderRoute: typeof AuthenticatedMiPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mis-convocatorias': {
      id: '/_authenticated/mis-convocatorias'
      path: '/mis-convocatorias'
      fullPath: '/mis-convocatorias'
      preLoaderRoute: typeof AuthenticatedMisConvocatoriasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mis-estadisticas': {
      id: '/_authenticated/mis-estadisticas'
      path: '/mis-estadisticas'
      fullPath: '/mis-estadisticas'
      preLoaderRoute: typeof AuthenticatedMisEstadisticasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/panel-fulltime': {
      id: '/_authenticated/panel-fulltime'
      path: '/panel-fulltime'
      fullPath: '/panel-fulltime'
      preLoaderRoute: typeof AuthenticatedPanelFulltimeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil-entrenador': {
      id: '/_authenticated/perfil-entrenador'
      path: '/perfil-entrenador'
      fullPath: '/perfil-entrenador'
      preLoaderRoute: typeof AuthenticatedPerfilEntrenadorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roster': {
      id: '/_authenticated/roster'
      path: '/roster'
      fullPath: '/roster'
      preLoaderRoute: typeof AuthenticatedRosterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/unirse-equipo/$token': {
      id: '/unirse-equipo/$token'
      path: '/unirse-equipo/$token'
      fullPath: '/unirse-equipo/$token'
      preLoaderRoute: typeof UnirseEquipoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unirse/$token': {
      id: '/unirse/$token'
      path: '/unirse/$token'
      fullPath: '/unirse/$token'
      preLoaderRoute: typeof UnirseTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/call-ups/': {
      id: '/_authenticated/call-ups/'
      path: '/'
      fullPath: '/call-ups/'
      preLoaderRoute: typeof AuthenticatedCallUpsIndexRouteImport
      parentRoute: typeof AuthenticatedCallUpsRoute
    }
    '/_authenticated/call-ups/$id': {
      id: '/_authenticated/call-ups/$id'
      path: '/$id'
      fullPath: '/call-ups/$id'
      preLoaderRoute: typeof AuthenticatedCallUpsIdRouteImport
      parentRoute: typeof AuthenticatedCallUpsRoute
    }
    '/_authenticated/call-ups/new': {
      id: '/_authenticated/call-ups/new'
      path: '/new'
      fullPath: '/call-ups/new'
      preLoaderRoute: typeof AuthenticatedCallUpsNewRouteImport
      parentRoute: typeof AuthenticatedCallUpsRoute
    }
    '/_authenticated/cotizacion/$id': {
      id: '/_authenticated/cotizacion/$id'
      path: '/cotizacion/$id'
      fullPath: '/cotizacion/$id'
      preLoaderRoute: typeof AuthenticatedCotizacionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entrenos/': {
      id: '/_authenticated/entrenos/'
      path: '/'
      fullPath: '/entrenos/'
      preLoaderRoute: typeof AuthenticatedEntrenosIndexRouteImport
      parentRoute: typeof AuthenticatedEntrenosRoute
    }
    '/_authenticated/entrenos/new': {
      id: '/_authenticated/entrenos/new'
      path: '/new'
      fullPath: '/entrenos/new'
      preLoaderRoute: typeof AuthenticatedEntrenosNewRouteImport
      parentRoute: typeof AuthenticatedEntrenosRoute
    }
    '/_authenticated/hoja/$id': {
      id: '/_authenticated/hoja/$id'
      path: '/hoja/$id'
      fullPath: '/hoja/$id'
      preLoaderRoute: typeof AuthenticatedHojaIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hq/': {
      id: '/_authenticated/hq/'
      path: '/'
      fullPath: '/hq/'
      preLoaderRoute: typeof AuthenticatedHqIndexRouteImport
      parentRoute: typeof AuthenticatedHqRoute
    }
    '/_authenticated/hq/$seccion': {
      id: '/_authenticated/hq/$seccion'
      path: '/$seccion'
      fullPath: '/hq/$seccion'
      preLoaderRoute: typeof AuthenticatedHqSeccionRouteImport
      parentRoute: typeof AuthenticatedHqRoute
    }
    '/_authenticated/hq/automatizaciones': {
      id: '/_authenticated/hq/automatizaciones'
      path: '/automatizaciones'
      fullPath: '/hq/automatizaciones'
      preLoaderRoute: typeof AuthenticatedHqAutomatizacionesRouteImport
      parentRoute: typeof AuthenticatedHqRoute
    }
    '/_authenticated/hq/calendario': {
      id: '/_authenticated/hq/calendario'
      path: '/calendario'
      fullPath: '/hq/calendario'
      preLoaderRoute: typeof AuthenticatedHqCalendarioRouteImport
      parentRoute: typeof AuthenticatedHqRoute
    }
    '/_authenticated/hq/contenido': {
      id: '/_authenticated/hq/contenido'
      path: '/contenido'
      fullPath: '/hq/contenido'
      preLoaderRoute: typeof AuthenticatedHqContenidoRouteImport
      parentRoute: typeof AuthenticatedHqRoute
    }
    '/_authenticated/hq/cotizaciones': {
      id: '/_authenticated/hq/cotizaciones'
      path: '/cotizaciones'
      fullPath: '/hq/cotizaciones'
      preLoaderRoute: typeof AuthenticatedHqCotizacionesRouteImport
      parentRoute: typeof AuthenticatedHqRoute
    }
    '/_authenticated/hq/crm': {
      id: '/_authenticated/hq/crm'
      path: '/crm'
      fullPath: '/hq/crm'
      preLoaderRoute: typeof AuthenticatedHqCrmRouteImport
      parentRoute: typeof AuthenticatedHqRoute
    }
    '/_authenticated/hq/inbox': {
      id: '/_authenticated/hq/inbox'
      path: '/inbox'
      fullPath: '/hq/inbox'
      preLoaderRoute: typeof AuthenticatedHqInboxRouteImport
      parentRoute: typeof AuthenticatedHqRoute
    }
    '/_authenticated/hq/notificaciones': {
      id: '/_authenticated/hq/notificaciones'
      path: '/notificaciones'
      fullPath: '/hq/notificaciones'
      preLoaderRoute: typeof AuthenticatedHqNotificacionesRouteImport
      parentRoute: typeof AuthenticatedHqRoute
    }
    '/_authenticated/hq/proyectos': {
      id: '/_authenticated/hq/proyectos'
      path: '/proyectos'
      fullPath: '/hq/proyectos'
      preLoaderRoute: typeof AuthenticatedHqProyectosRouteImport
      parentRoute: typeof AuthenticatedHqRoute
    }
    '/_authenticated/hq/reuniones': {
      id: '/_authenticated/hq/reuniones'
      path: '/reuniones'
      fullPath: '/hq/reuniones'
      preLoaderRoute: typeof AuthenticatedHqReunionesRouteImport
      parentRoute: typeof AuthenticatedHqRoute
    }
    '/_authenticated/hq/tareas': {
      id: '/_authenticated/hq/tareas'
      path: '/tareas'
      fullPath: '/hq/tareas'
      preLoaderRoute: typeof AuthenticatedHqTareasRouteImport
      parentRoute: typeof AuthenticatedHqRoute
    }
    '/api/public/cron/reminders': {
      id: '/api/public/cron/reminders'
      path: '/api/public/cron/reminders'
      fullPath: '/api/public/cron/reminders'
      preLoaderRoute: typeof ApiPublicCronRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedCallUpsRouteChildren {
  AuthenticatedCallUpsIdRoute: typeof AuthenticatedCallUpsIdRoute
  AuthenticatedCallUpsNewRoute: typeof AuthenticatedCallUpsNewRoute
  AuthenticatedCallUpsIndexRoute: typeof AuthenticatedCallUpsIndexRoute
}

const AuthenticatedCallUpsRouteChildren: AuthenticatedCallUpsRouteChildren = {
  AuthenticatedCallUpsIdRoute: AuthenticatedCallUpsIdRoute,
  AuthenticatedCallUpsNewRoute: AuthenticatedCallUpsNewRoute,
  AuthenticatedCallUpsIndexRoute: AuthenticatedCallUpsIndexRoute,
}

const AuthenticatedCallUpsRouteWithChildren =
  AuthenticatedCallUpsRoute._addFileChildren(AuthenticatedCallUpsRouteChildren)

interface AuthenticatedEntrenosRouteChildren {
  AuthenticatedEntrenosNewRoute: typeof AuthenticatedEntrenosNewRoute
  AuthenticatedEntrenosIndexRoute: typeof AuthenticatedEntrenosIndexRoute
}

const AuthenticatedEntrenosRouteChildren: AuthenticatedEntrenosRouteChildren = {
  AuthenticatedEntrenosNewRoute: AuthenticatedEntrenosNewRoute,
  AuthenticatedEntrenosIndexRoute: AuthenticatedEntrenosIndexRoute,
}

const AuthenticatedEntrenosRouteWithChildren =
  AuthenticatedEntrenosRoute._addFileChildren(
    AuthenticatedEntrenosRouteChildren,
  )

interface AuthenticatedHqRouteChildren {
  AuthenticatedHqSeccionRoute: typeof AuthenticatedHqSeccionRoute
  AuthenticatedHqAutomatizacionesRoute: typeof AuthenticatedHqAutomatizacionesRoute
  AuthenticatedHqCalendarioRoute: typeof AuthenticatedHqCalendarioRoute
  AuthenticatedHqContenidoRoute: typeof AuthenticatedHqContenidoRoute
  AuthenticatedHqCotizacionesRoute: typeof AuthenticatedHqCotizacionesRoute
  AuthenticatedHqCrmRoute: typeof AuthenticatedHqCrmRoute
  AuthenticatedHqInboxRoute: typeof AuthenticatedHqInboxRoute
  AuthenticatedHqNotificacionesRoute: typeof AuthenticatedHqNotificacionesRoute
  AuthenticatedHqProyectosRoute: typeof AuthenticatedHqProyectosRoute
  AuthenticatedHqReunionesRoute: typeof AuthenticatedHqReunionesRoute
  AuthenticatedHqTareasRoute: typeof AuthenticatedHqTareasRoute
  AuthenticatedHqIndexRoute: typeof AuthenticatedHqIndexRoute
}

const AuthenticatedHqRouteChildren: AuthenticatedHqRouteChildren = {
  AuthenticatedHqSeccionRoute: AuthenticatedHqSeccionRoute,
  AuthenticatedHqAutomatizacionesRoute: AuthenticatedHqAutomatizacionesRoute,
  AuthenticatedHqCalendarioRoute: AuthenticatedHqCalendarioRoute,
  AuthenticatedHqContenidoRoute: AuthenticatedHqContenidoRoute,
  AuthenticatedHqCotizacionesRoute: AuthenticatedHqCotizacionesRoute,
  AuthenticatedHqCrmRoute: AuthenticatedHqCrmRoute,
  AuthenticatedHqInboxRoute: AuthenticatedHqInboxRoute,
  AuthenticatedHqNotificacionesRoute: AuthenticatedHqNotificacionesRoute,
  AuthenticatedHqProyectosRoute: AuthenticatedHqProyectosRoute,
  AuthenticatedHqReunionesRoute: AuthenticatedHqReunionesRoute,
  AuthenticatedHqTareasRoute: AuthenticatedHqTareasRoute,
  AuthenticatedHqIndexRoute: AuthenticatedHqIndexRoute,
}

const AuthenticatedHqRouteWithChildren = AuthenticatedHqRoute._addFileChildren(
  AuthenticatedHqRouteChildren,
)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAsistenciaRoute: typeof AuthenticatedAsistenciaRoute
  AuthenticatedBienestarRoute: typeof AuthenticatedBienestarRoute
  AuthenticatedCalendarioRoute: typeof AuthenticatedCalendarioRoute
  AuthenticatedCallUpsRoute: typeof AuthenticatedCallUpsRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEntrenosRoute: typeof AuthenticatedEntrenosRouteWithChildren
  AuthenticatedEquipoRoute: typeof AuthenticatedEquipoRoute
  AuthenticatedEstadisticasRoute: typeof AuthenticatedEstadisticasRoute
  AuthenticatedFormulariosRoute: typeof AuthenticatedFormulariosRoute
  AuthenticatedHqRoute: typeof AuthenticatedHqRouteWithChildren
  AuthenticatedInicioRoute: typeof AuthenticatedInicioRoute
  AuthenticatedMiCalendarioRoute: typeof AuthenticatedMiCalendarioRoute
  AuthenticatedMiPerfilRoute: typeof AuthenticatedMiPerfilRoute
  AuthenticatedMisConvocatoriasRoute: typeof AuthenticatedMisConvocatoriasRoute
  AuthenticatedMisEstadisticasRoute: typeof AuthenticatedMisEstadisticasRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPanelFulltimeRoute: typeof AuthenticatedPanelFulltimeRoute
  AuthenticatedPerfilEntrenadorRoute: typeof AuthenticatedPerfilEntrenadorRoute
  AuthenticatedRosterRoute: typeof AuthenticatedRosterRoute
  AuthenticatedCotizacionIdRoute: typeof AuthenticatedCotizacionIdRoute
  AuthenticatedHojaIdRoute: typeof AuthenticatedHojaIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAsistenciaRoute: AuthenticatedAsistenciaRoute,
  AuthenticatedBienestarRoute: AuthenticatedBienestarRoute,
  AuthenticatedCalendarioRoute: AuthenticatedCalendarioRoute,
  AuthenticatedCallUpsRoute: AuthenticatedCallUpsRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEntrenosRoute: AuthenticatedEntrenosRouteWithChildren,
  AuthenticatedEquipoRoute: AuthenticatedEquipoRoute,
  AuthenticatedEstadisticasRoute: AuthenticatedEstadisticasRoute,
  AuthenticatedFormulariosRoute: AuthenticatedFormulariosRoute,
  AuthenticatedHqRoute: AuthenticatedHqRouteWithChildren,
  AuthenticatedInicioRoute: AuthenticatedInicioRoute,
  AuthenticatedMiCalendarioRoute: AuthenticatedMiCalendarioRoute,
  AuthenticatedMiPerfilRoute: AuthenticatedMiPerfilRoute,
  AuthenticatedMisConvocatoriasRoute: AuthenticatedMisConvocatoriasRoute,
  AuthenticatedMisEstadisticasRoute: AuthenticatedMisEstadisticasRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPanelFulltimeRoute: AuthenticatedPanelFulltimeRoute,
  AuthenticatedPerfilEntrenadorRoute: AuthenticatedPerfilEntrenadorRoute,
  AuthenticatedRosterRoute: AuthenticatedRosterRoute,
  AuthenticatedCotizacionIdRoute: AuthenticatedCotizacionIdRoute,
  AuthenticatedHojaIdRoute: AuthenticatedHojaIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  AyudaRoute: AyudaRoute,
  PrivacidadRoute: PrivacidadRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  UnirseEquipoTokenRoute: UnirseEquipoTokenRoute,
  UnirseTokenRoute: UnirseTokenRoute,
  ApiPublicCronRemindersRoute: ApiPublicCronRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
