/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UnirseTokenRouteImport } from './routes/unirse.$token'
import { Route as UnirseEquipoTokenRouteImport } from './routes/unirse-equipo.$token'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedRosterRouteImport } from './routes/_authenticated/roster'
import { Route as AuthenticatedPerfilEntrenadorRouteImport } from './routes/_authenticated/perfil-entrenador'
import { Route as AuthenticatedPanelFulltimeRouteImport } from './routes/_authenticated/panel-fulltime'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedMisConvocatoriasRouteImport } from './routes/_authenticated/mis-convocatorias'
import { Route as AuthenticatedMiPerfilRouteImport } from './routes/_authenticated/mi-perfil'
import { Route as AuthenticatedInicioRouteImport } from './routes/_authenticated/inicio'
import { Route as AuthenticatedEquipoRouteImport } from './routes/_authenticated/equipo'
import { Route as AuthenticatedEntrenosRouteImport } from './routes/_authenticated/entrenos'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCallUpsRouteImport } from './routes/_authenticated/call-ups'
import { Route as AuthenticatedCalendarioRouteImport } from './routes/_authenticated/calendario'
import { Route as AuthenticatedAsistenciaRouteImport } from './routes/_authenticated/asistencia'
import { Route as AuthenticatedEntrenosIndexRouteImport } from './routes/_authenticated/entrenos.index'
import { Route as AuthenticatedCallUpsIndexRouteImport } from './routes/_authenticated/call-ups.index'
import { Route as AuthenticatedEntrenosNewRouteImport } from './routes/_authenticated/entrenos.new'
import { Route as AuthenticatedCallUpsNewRouteImport } from './routes/_authenticated/call-ups.new'
import { Route as AuthenticatedCallUpsIdRouteImport } from './routes/_authenticated/call-ups.$id'
import { Route as ApiPublicCronRemindersRouteImport } from './routes/api/public/cron/reminders'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnirseTokenRoute = UnirseTokenRouteImport.update({
  id: '/unirse/$token',
  path: '/unirse/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const UnirseEquipoTokenRoute = UnirseEquipoTokenRouteImport.update({
  id: '/unirse-equipo/$token',
  path: '/unirse-equipo/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedRosterRoute = AuthenticatedRosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilEntrenadorRoute =
  AuthenticatedPerfilEntrenadorRouteImport.update({
    id: '/perfil-entrenador',
    path: '/perfil-entrenador',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPanelFulltimeRoute =
  AuthenticatedPanelFulltimeRouteImport.update({
    id: '/panel-fulltime',
    path: '/panel-fulltime',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMisConvocatoriasRoute =
  AuthenticatedMisConvocatoriasRouteImport.update({
    id: '/mis-convocatorias',
    path: '/mis-convocatorias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMiPerfilRoute = AuthenticatedMiPerfilRouteImport.update({
  id: '/mi-perfil',
  path: '/mi-perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInicioRoute = AuthenticatedInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEquipoRoute = AuthenticatedEquipoRouteImport.update({
  id: '/equipo',
  path: '/equipo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEntrenosRoute = AuthenticatedEntrenosRouteImport.update({
  id: '/entrenos',
  path: '/entrenos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCallUpsRoute = AuthenticatedCallUpsRouteImport.update({
  id: '/call-ups',
  path: '/call-ups',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarioRoute = AuthenticatedCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAsistenciaRoute = AuthenticatedAsistenciaRouteImport.update({
  id: '/asistencia',
  path: '/asistencia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEntrenosIndexRoute =
  AuthenticatedEntrenosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEntrenosRoute,
  } as any)
const AuthenticatedCallUpsIndexRoute =
  AuthenticatedCallUpsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCallUpsRoute,
  } as any)
const AuthenticatedEntrenosNewRoute =
  AuthenticatedEntrenosNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedEntrenosRoute,
  } as any)
const AuthenticatedCallUpsNewRoute = AuthenticatedCallUpsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedCallUpsRoute,
} as any)
const AuthenticatedCallUpsIdRoute = AuthenticatedCallUpsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedCallUpsRoute,
} as any)
const ApiPublicCronRemindersRoute = ApiPublicCronRemindersRouteImport.update({
  id: '/api/public/cron/reminders',
  path: '/api/public/cron/reminders',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/asistencia': typeof AuthenticatedAsistenciaRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/call-ups': typeof AuthenticatedCallUpsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/entrenos': typeof AuthenticatedEntrenosRouteWithChildren
  '/equipo': typeof AuthenticatedEquipoRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/mi-perfil': typeof AuthenticatedMiPerfilRoute
  '/mis-convocatorias': typeof AuthenticatedMisConvocatoriasRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/panel-fulltime': typeof AuthenticatedPanelFulltimeRoute
  '/perfil-entrenador': typeof AuthenticatedPerfilEntrenadorRoute
  '/roster': typeof AuthenticatedRosterRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/unirse-equipo/$token': typeof UnirseEquipoTokenRoute
  '/unirse/$token': typeof UnirseTokenRoute
  '/call-ups/$id': typeof AuthenticatedCallUpsIdRoute
  '/call-ups/new': typeof AuthenticatedCallUpsNewRoute
  '/entrenos/new': typeof AuthenticatedEntrenosNewRoute
  '/call-ups/': typeof AuthenticatedCallUpsIndexRoute
  '/entrenos/': typeof AuthenticatedEntrenosIndexRoute
  '/api/public/cron/reminders': typeof ApiPublicCronRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/asistencia': typeof AuthenticatedAsistenciaRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/equipo': typeof AuthenticatedEquipoRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/mi-perfil': typeof AuthenticatedMiPerfilRoute
  '/mis-convocatorias': typeof AuthenticatedMisConvocatoriasRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/panel-fulltime': typeof AuthenticatedPanelFulltimeRoute
  '/perfil-entrenador': typeof AuthenticatedPerfilEntrenadorRoute
  '/roster': typeof AuthenticatedRosterRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/unirse-equipo/$token': typeof UnirseEquipoTokenRoute
  '/unirse/$token': typeof UnirseTokenRoute
  '/call-ups/$id': typeof AuthenticatedCallUpsIdRoute
  '/call-ups/new': typeof AuthenticatedCallUpsNewRoute
  '/entrenos/new': typeof AuthenticatedEntrenosNewRoute
  '/call-ups': typeof AuthenticatedCallUpsIndexRoute
  '/entrenos': typeof AuthenticatedEntrenosIndexRoute
  '/api/public/cron/reminders': typeof ApiPublicCronRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/asistencia': typeof AuthenticatedAsistenciaRoute
  '/_authenticated/calendario': typeof AuthenticatedCalendarioRoute
  '/_authenticated/call-ups': typeof AuthenticatedCallUpsRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/entrenos': typeof AuthenticatedEntrenosRouteWithChildren
  '/_authenticated/equipo': typeof AuthenticatedEquipoRoute
  '/_authenticated/inicio': typeof AuthenticatedInicioRoute
  '/_authenticated/mi-perfil': typeof AuthenticatedMiPerfilRoute
  '/_authenticated/mis-convocatorias': typeof AuthenticatedMisConvocatoriasRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/panel-fulltime': typeof AuthenticatedPanelFulltimeRoute
  '/_authenticated/perfil-entrenador': typeof AuthenticatedPerfilEntrenadorRoute
  '/_authenticated/roster': typeof AuthenticatedRosterRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/unirse-equipo/$token': typeof UnirseEquipoTokenRoute
  '/unirse/$token': typeof UnirseTokenRoute
  '/_authenticated/call-ups/$id': typeof AuthenticatedCallUpsIdRoute
  '/_authenticated/call-ups/new': typeof AuthenticatedCallUpsNewRoute
  '/_authenticated/entrenos/new': typeof AuthenticatedEntrenosNewRoute
  '/_authenticated/call-ups/': typeof AuthenticatedCallUpsIndexRoute
  '/_authenticated/entrenos/': typeof AuthenticatedEntrenosIndexRoute
  '/api/public/cron/reminders': typeof ApiPublicCronRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/asistencia'
    | '/calendario'
    | '/call-ups'
    | '/dashboard'
    | '/entrenos'
    | '/equipo'
    | '/inicio'
    | '/mi-perfil'
    | '/mis-convocatorias'
    | '/onboarding'
    | '/panel-fulltime'
    | '/perfil-entrenador'
    | '/roster'
    | '/auth/callback'
    | '/unirse-equipo/$token'
    | '/unirse/$token'
    | '/call-ups/$id'
    | '/call-ups/new'
    | '/entrenos/new'
    | '/call-ups/'
    | '/entrenos/'
    | '/api/public/cron/reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/asistencia'
    | '/calendario'
    | '/dashboard'
    | '/equipo'
    | '/inicio'
    | '/mi-perfil'
    | '/mis-convocatorias'
    | '/onboarding'
    | '/panel-fulltime'
    | '/perfil-entrenador'
    | '/roster'
    | '/auth/callback'
    | '/unirse-equipo/$token'
    | '/unirse/$token'
    | '/call-ups/$id'
    | '/call-ups/new'
    | '/entrenos/new'
    | '/call-ups'
    | '/entrenos'
    | '/api/public/cron/reminders'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/asistencia'
    | '/_authenticated/calendario'
    | '/_authenticated/call-ups'
    | '/_authenticated/dashboard'
    | '/_authenticated/entrenos'
    | '/_authenticated/equipo'
    | '/_authenticated/inicio'
    | '/_authenticated/mi-perfil'
    | '/_authenticated/mis-convocatorias'
    | '/_authenticated/onboarding'
    | '/_authenticated/panel-fulltime'
    | '/_authenticated/perfil-entrenador'
    | '/_authenticated/roster'
    | '/auth/callback'
    | '/unirse-equipo/$token'
    | '/unirse/$token'
    | '/_authenticated/call-ups/$id'
    | '/_authenticated/call-ups/new'
    | '/_authenticated/entrenos/new'
    | '/_authenticated/call-ups/'
    | '/_authenticated/entrenos/'
    | '/api/public/cron/reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  UnirseEquipoTokenRoute: typeof UnirseEquipoTokenRoute
  UnirseTokenRoute: typeof UnirseTokenRoute
  ApiPublicCronRemindersRoute: typeof ApiPublicCronRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unirse/$token': {
      id: '/unirse/$token'
      path: '/unirse/$token'
      fullPath: '/unirse/$token'
      preLoaderRoute: typeof UnirseTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unirse-equipo/$token': {
      id: '/unirse-equipo/$token'
      path: '/unirse-equipo/$token'
      fullPath: '/unirse-equipo/$token'
      preLoaderRoute: typeof UnirseEquipoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/roster': {
      id: '/_authenticated/roster'
      path: '/roster'
      fullPath: '/roster'
      preLoaderRoute: typeof AuthenticatedRosterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil-entrenador': {
      id: '/_authenticated/perfil-entrenador'
      path: '/perfil-entrenador'
      fullPath: '/perfil-entrenador'
      preLoaderRoute: typeof AuthenticatedPerfilEntrenadorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/panel-fulltime': {
      id: '/_authenticated/panel-fulltime'
      path: '/panel-fulltime'
      fullPath: '/panel-fulltime'
      preLoaderRoute: typeof AuthenticatedPanelFulltimeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mis-convocatorias': {
      id: '/_authenticated/mis-convocatorias'
      path: '/mis-convocatorias'
      fullPath: '/mis-convocatorias'
      preLoaderRoute: typeof AuthenticatedMisConvocatoriasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mi-perfil': {
      id: '/_authenticated/mi-perfil'
      path: '/mi-perfil'
      fullPath: '/mi-perfil'
      preLoaderRoute: typeof AuthenticatedMiPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inicio': {
      id: '/_authenticated/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof AuthenticatedInicioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipo': {
      id: '/_authenticated/equipo'
      path: '/equipo'
      fullPath: '/equipo'
      preLoaderRoute: typeof AuthenticatedEquipoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entrenos': {
      id: '/_authenticated/entrenos'
      path: '/entrenos'
      fullPath: '/entrenos'
      preLoaderRoute: typeof AuthenticatedEntrenosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/call-ups': {
      id: '/_authenticated/call-ups'
      path: '/call-ups'
      fullPath: '/call-ups'
      preLoaderRoute: typeof AuthenticatedCallUpsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendario': {
      id: '/_authenticated/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AuthenticatedCalendarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/asistencia': {
      id: '/_authenticated/asistencia'
      path: '/asistencia'
      fullPath: '/asistencia'
      preLoaderRoute: typeof AuthenticatedAsistenciaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entrenos/': {
      id: '/_authenticated/entrenos/'
      path: '/'
      fullPath: '/entrenos/'
      preLoaderRoute: typeof AuthenticatedEntrenosIndexRouteImport
      parentRoute: typeof AuthenticatedEntrenosRoute
    }
    '/_authenticated/call-ups/': {
      id: '/_authenticated/call-ups/'
      path: '/'
      fullPath: '/call-ups/'
      preLoaderRoute: typeof AuthenticatedCallUpsIndexRouteImport
      parentRoute: typeof AuthenticatedCallUpsRoute
    }
    '/_authenticated/entrenos/new': {
      id: '/_authenticated/entrenos/new'
      path: '/new'
      fullPath: '/entrenos/new'
      preLoaderRoute: typeof AuthenticatedEntrenosNewRouteImport
      parentRoute: typeof AuthenticatedEntrenosRoute
    }
    '/_authenticated/call-ups/new': {
      id: '/_authenticated/call-ups/new'
      path: '/new'
      fullPath: '/call-ups/new'
      preLoaderRoute: typeof AuthenticatedCallUpsNewRouteImport
      parentRoute: typeof AuthenticatedCallUpsRoute
    }
    '/_authenticated/call-ups/$id': {
      id: '/_authenticated/call-ups/$id'
      path: '/$id'
      fullPath: '/call-ups/$id'
      preLoaderRoute: typeof AuthenticatedCallUpsIdRouteImport
      parentRoute: typeof AuthenticatedCallUpsRoute
    }
    '/api/public/cron/reminders': {
      id: '/api/public/cron/reminders'
      path: '/api/public/cron/reminders'
      fullPath: '/api/public/cron/reminders'
      preLoaderRoute: typeof ApiPublicCronRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedCallUpsRouteChildren {
  AuthenticatedCallUpsIdRoute: typeof AuthenticatedCallUpsIdRoute
  AuthenticatedCallUpsNewRoute: typeof AuthenticatedCallUpsNewRoute
  AuthenticatedCallUpsIndexRoute: typeof AuthenticatedCallUpsIndexRoute
}

const AuthenticatedCallUpsRouteChildren: AuthenticatedCallUpsRouteChildren = {
  AuthenticatedCallUpsIdRoute: AuthenticatedCallUpsIdRoute,
  AuthenticatedCallUpsNewRoute: AuthenticatedCallUpsNewRoute,
  AuthenticatedCallUpsIndexRoute: AuthenticatedCallUpsIndexRoute,
}

const AuthenticatedCallUpsRouteWithChildren =
  AuthenticatedCallUpsRoute._addFileChildren(AuthenticatedCallUpsRouteChildren)

interface AuthenticatedEntrenosRouteChildren {
  AuthenticatedEntrenosNewRoute: typeof AuthenticatedEntrenosNewRoute
  AuthenticatedEntrenosIndexRoute: typeof AuthenticatedEntrenosIndexRoute
}

const AuthenticatedEntrenosRouteChildren: AuthenticatedEntrenosRouteChildren = {
  AuthenticatedEntrenosNewRoute: AuthenticatedEntrenosNewRoute,
  AuthenticatedEntrenosIndexRoute: AuthenticatedEntrenosIndexRoute,
}

const AuthenticatedEntrenosRouteWithChildren =
  AuthenticatedEntrenosRoute._addFileChildren(
    AuthenticatedEntrenosRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAsistenciaRoute: typeof AuthenticatedAsistenciaRoute
  AuthenticatedCalendarioRoute: typeof AuthenticatedCalendarioRoute
  AuthenticatedCallUpsRoute: typeof AuthenticatedCallUpsRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEntrenosRoute: typeof AuthenticatedEntrenosRouteWithChildren
  AuthenticatedEquipoRoute: typeof AuthenticatedEquipoRoute
  AuthenticatedInicioRoute: typeof AuthenticatedInicioRoute
  AuthenticatedMiPerfilRoute: typeof AuthenticatedMiPerfilRoute
  AuthenticatedMisConvocatoriasRoute: typeof AuthenticatedMisConvocatoriasRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPanelFulltimeRoute: typeof AuthenticatedPanelFulltimeRoute
  AuthenticatedPerfilEntrenadorRoute: typeof AuthenticatedPerfilEntrenadorRoute
  AuthenticatedRosterRoute: typeof AuthenticatedRosterRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAsistenciaRoute: AuthenticatedAsistenciaRoute,
  AuthenticatedCalendarioRoute: AuthenticatedCalendarioRoute,
  AuthenticatedCallUpsRoute: AuthenticatedCallUpsRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEntrenosRoute: AuthenticatedEntrenosRouteWithChildren,
  AuthenticatedEquipoRoute: AuthenticatedEquipoRoute,
  AuthenticatedInicioRoute: AuthenticatedInicioRoute,
  AuthenticatedMiPerfilRoute: AuthenticatedMiPerfilRoute,
  AuthenticatedMisConvocatoriasRoute: AuthenticatedMisConvocatoriasRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPanelFulltimeRoute: AuthenticatedPanelFulltimeRoute,
  AuthenticatedPerfilEntrenadorRoute: AuthenticatedPerfilEntrenadorRoute,
  AuthenticatedRosterRoute: AuthenticatedRosterRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  UnirseEquipoTokenRoute: UnirseEquipoTokenRoute,
  UnirseTokenRoute: UnirseTokenRoute,
  ApiPublicCronRemindersRoute: ApiPublicCronRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
